version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/Simple-dotnet8/Simple-dotnet8"
    schedule:
      interval: "daily"
      time: "14:50"  # Approximate time in 24-hour format, UTC is the default timezone
    allow:
      - dependency-name: "Newtonsoft.Json"