name: Buid and Publish
on: 
  pull_request:
  workflow_call:
    inputs:
      version:
        description: 'Release version (SemVer, e.g. 1.2.3)'
        required: true
        type: string
  workflow_dispatch:

jobs:
  dummy:
    name: Dummy job
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Just test
        run: |
          echo "It's a job for learning purposes"
          Write-Host "${{ github.ref_name }}"
          Write-Host "${{ github.event_name }}"
          Write-Host "${{ inputs.version }}"